fastlane_version '2.53.1'

before_all do
  ensure_git_branch
  ensure_git_status_clean
  git_pull
end

platform :ios do
   # iOS Lanes
   desc "Bump and tag version"
   lane :bump do
     bump_message = "Bump build number."
     # If our latest commit isn't a build bump, then bump the build.
     build_is_already_bumped = last_git_commit[:message].include? bump_message
     next if build_is_already_bumped
     increment_build_number
     commit_version_bump(
       message: bump_message,
       xcodeproj: "Project.xcodeproj"
     )
     add_git_tag
     push_to_git_remote
   end
end

platform :android do
  # Android Lanes
end
